# Generated by Django 5.2.3 on 2025-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_telegramusers_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramusers',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
